/**** BEGIN COPYRIGHT ********************************************************
 *
 * Copyright (C) 2007 - 2012, Rogvall Invest AB, <tony@rogvall.se>
 *
 * This software is licensed as described in the file COPYRIGHT, which
 * you should have received as part of this distribution. The terms
 * are also available at http://www.rogvall.se/docs/copyright.txt.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYRIGHT file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 **** END COPYRIGHT **********************************************************/
// Generated by eapi (DO NOT EDIT)
#ifndef __CAN_SOCK_DRV_H__
#define __CAN_SOCK_DRV_H__

struct i_can_frame {
  uint32_t id;
  uint8_t len;
  eapi_binary_t data;
  int intf;
  int ts;

};
extern void r_struct_i_can_frame(eapi_ctx_t* ctx, struct i_can_frame *ptr);
extern int d_struct_i_can_frame(eapi_ctx_t* ctx, cbuf_t* c_in, struct i_can_frame *ptr);
#define CAN_SOCK_DRV_CMD_IFNAME 1
extern void can_sock_drv_impl_ifname(eapi_ctx_t* ctx,cbuf_t* c_out,int index);
#define CAN_SOCK_DRV_CMD_IFINDEX 2
extern void can_sock_drv_impl_ifindex(eapi_ctx_t* ctx,cbuf_t* c_out,eapi_string_t* name);
#define CAN_SOCK_DRV_CMD_SET_ERROR_FILTER 3
extern void can_sock_drv_impl_set_error_filter(eapi_ctx_t* ctx,cbuf_t* c_out,uint32_t mask);
#define CAN_SOCK_DRV_CMD_SET_LOOPBACK 4
extern void can_sock_drv_impl_set_loopback(eapi_ctx_t* ctx,cbuf_t* c_out,uint8_t enable);
#define CAN_SOCK_DRV_CMD_RECV_OWN_MESSAGES 5
extern void can_sock_drv_impl_recv_own_messages(eapi_ctx_t* ctx,cbuf_t* c_out,uint8_t enable);
#define CAN_SOCK_DRV_CMD_BIND 6
extern void can_sock_drv_impl_bind(eapi_ctx_t* ctx,cbuf_t* c_out,int index);
#define CAN_SOCK_DRV_CMD_SEND 7
extern void can_sock_drv_impl_send(eapi_ctx_t* ctx,cbuf_t* c_out,int index,struct i_can_frame* frame);
#endif
