%%%---- BEGIN COPYRIGHT --------------------------------------------------------
%%%
%%% Copyright (C) 2007 - 2012, Rogvall Invest AB, <tony@rogvall.se>
%%%
%%% This software is licensed as described in the file COPYRIGHT, which
%%% you should have received as part of this distribution. The terms
%%% are also available at http://www.rogvall.se/docs/copyright.txt.
%%%
%%% You may opt to use, copy, modify, merge, publish, distribute and/or sell
%%% copies of the Software, and permit persons to whom the Software is
%%% furnished to do so, under the terms of the COPYRIGHT file.
%%%
%%% This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
%%% KIND, either express or implied.
%%%
%%%---- END COPYRIGHT ----------------------------------------------------------
%% Generated by eapi (DO NOT EDIT)
-ifndef(__CAN_SOCK_DRV_HRL__).
-define(__CAN_SOCK_DRV_HRL__,true).
-define(CAN_SOCK_DRV_CMD_IFNAME,1).
-define(CAN_SOCK_DRV_CMD_IFINDEX,2).
-define(CAN_SOCK_DRV_CMD_SET_ERROR_FILTER,3).
-define(CAN_SOCK_DRV_CMD_SET_LOOPBACK,4).
-define(CAN_SOCK_DRV_CMD_RECV_OWN_MESSAGES,5).
-define(CAN_SOCK_DRV_CMD_BIND,6).
-define(CAN_SOCK_DRV_CMD_SEND,7).
-define(CAN_SOCK_DRV_CMD_SET_FILTER,8).
-endif.
