%% Generated by eapi (DO NOT EDIT)
-module(can_sock).

-export([start_link/0, start/0, stop/0]).
-export([start_link/1, start/1]).
-export([set_loopback/1]).
-export([ifindex/1]).
-export([ifname/1]).
-export([bind/1]).
-export([send/1]).
-export([recv_own_messages/1]).
-export([set_error_filter/1]).
-include_lib("eapi/include/cbuf.hrl").
-include("can_sock.hrl").

start_link() ->
  start_link([]).

start_link(Opts) ->
  eapi_drv:start_link([
    {srv_name, can_sock_srv},
    {prt_name, can_sock_prt},
    {reg_name, can_sock_reg},
    {driver_name, "can_sock_drv"},
    {app, can_sock} | Opts]).

start() ->
  start([]).

start(Opts) ->
  eapi_drv:start([
    {srv_name, can_sock_srv},
    {prt_name, can_sock_prt},
    {reg_name, can_sock_reg},
    {driver_name, "can_sock_drv"},
    {app, can_sock}|Opts]).

stop() ->
  eapi_drv:stop(can_sock_srv).

e_struct_can_frame_t(R)->
  Rtr__bool=if (R#can_frame_t.rtr) -> 1; true -> 0 end,
  Ext__bool=if (R#can_frame_t.ext) -> 1; true -> 0 end,
  Data__size = byte_size(R#can_frame_t.data),  <<?uint32_t((R#can_frame_t.id)),?int_t(Rtr__bool),?int_t(Ext__bool),?int_t((R#can_frame_t.intf)),?uint8_t((R#can_frame_t.len)),?uint32_t(Data__size),(R#can_frame_t.data)/binary>>.

ifname(Index) -> 
 eapi_drv:command(can_sock_prt,?CAN_SOCK_DRV_CMD_IFNAME, [<<?int_t((Index))>>]).
ifindex(String_t) -> 
 eapi_drv:command(can_sock_prt,?CAN_SOCK_DRV_CMD_IFINDEX, [<<?int_t((String_t))>>]).
set_error_filter(Mask) -> 
 eapi_drv:command(can_sock_prt,?CAN_SOCK_DRV_CMD_SET_ERROR_FILTER, [<<?uint32_t((Mask))>>]).
set_loopback(Enable) -> 
  Enable__bool=if (Enable) -> 1; true -> 0 end,
 eapi_drv:command(can_sock_prt,?CAN_SOCK_DRV_CMD_SET_LOOPBACK, [<<?int_t(Enable__bool)>>]).
recv_own_messages(Enable) -> 
  Enable__bool=if (Enable) -> 1; true -> 0 end,
 eapi_drv:command(can_sock_prt,?CAN_SOCK_DRV_CMD_RECV_OWN_MESSAGES, [<<?int_t(Enable__bool)>>]).
bind(Index) -> 
 eapi_drv:command(can_sock_prt,?CAN_SOCK_DRV_CMD_BIND, [<<?int_t((Index))>>]).
send(Frame) -> 
  Frame__bin = list_to_binary(e_struct_can_frame_t(Frame)),Frame__size = byte_size(Frame__bin),
 eapi_drv:command(can_sock_prt,?CAN_SOCK_DRV_CMD_SEND, [<<?uint32_t(Frame__size),Frame__bin/binary>>]).
